---
apiVersion: v1
kind: Namespace
metadata:
  name: fortune
---
apiVersion: v1
kind: Service
metadata:
  name: fortune-service
  namespace: fortune
  labels:
    app: fortune-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: fortune-app
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: fortune
  labels:
    app: redis
spec:
  ports:
  - port: 6379
  type: LoadBalancer
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-app
  namespace: fortune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune-app
  template:
    metadata:
      name: fortune-app
      annotations:
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: fortune-app
    spec:
      containers:
      - image: howardyoo/fortune-demo:latest
        name: fortune-app
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_REDIS_HOST
          value: "redis.fortune.svc.cluster.local"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: fortune
spec:
  replicas: 1
  serviceName: "redis"
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
      - image: redis:latest
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
